name = "glazed_corn"
version = "1.0.0"
description = "Corn parser implemented in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "corn-config", repo = "glazed-corn" }
links = [{ title = "Website", href = "https://cornlang.dev/" }]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
splitter = ">= 1.0.0 and < 2.0.0"
envoy = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
filepath = ">= 1.1.2 and < 2.0.0"
